version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: bensbot-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    volumes:
      - ./trading_bot:/app/trading_bot
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: bensbot-dashboard
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy

volumes:
  app-data:
  logs:
  
networks:
  default:
    name: bensbot-network
