# AI Service API Keys - KEEP SECURE
# Do not commit this file to version control

openai: "YOUR_OPENAI_API_KEY"
anthropic: "YOUR_ANTHROPIC_API_KEY"
mistral: ""  # Add your Mistral key if you have one
